root: true

env:
  browser: true

rules:
  # Possible Errors
  # http://eslint.org/docs/rules/#possible-errors
  for-direction: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-semi: error
  no-func-assign: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-obj-calls: error

  # Stylistic Issues
  # http://eslint.org/docs/rules/#stylistic-issues
  linebreak-style: [error, unix]
